#!/bin/bash

TIME=`date +%s`

#for benchmark in cassandra ; do
#for benchmark in cassandra classification cloud9 cloudstone nutch streaming ; do
for benchmark in cassandra classification nutch ; do
    for ii in `seq 7`; do
	for cfg in addr_128rows addr_256rows addr_512rows addr addr_2krows addr_4krows addr_8krows; do
	    JOBNAME=${TIME}_${benchmark}_${cfg}_scheme${ii}
	    /usr/bin/time -v ./scripts/run_job -run timing -cfg ${cfg} -local -ma -runfxpt 0:1-4 -job ${JOBNAME} -state mwm126/mystate CMP.L2SharedNUCA.DRAMSim.OoO ${benchmark} 2>&1 | tee results/${JOBNAME}.log &
	done
	wait
    done
done

